CREATE TABLE IF NOT EXISTS collection_batches (
  id BIGINT NOT NULL AUTO_INCREMENT,
  batch_no VARCHAR(64) NOT NULL,
  trigger_type VARCHAR(32) NOT NULL,
  target_address VARCHAR(128) NOT NULL,
  chain_key VARCHAR(32) NULL,
  coin_symbol VARCHAR(32) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  total_tasks INT NOT NULL DEFAULT 0,
  success_tasks INT NOT NULL DEFAULT 0,
  failed_tasks INT NOT NULL DEFAULT 0,
  skipped_tasks INT NOT NULL DEFAULT 0,
  total_amount DECIMAL(36,18) NOT NULL DEFAULT 0,
  success_amount DECIMAL(36,18) NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  created_by BIGINT NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_collection_batches_batch_no (batch_no),
  KEY idx_collection_batches_status (status),
  KEY idx_collection_batches_chain_coin (chain_key, coin_symbol),
  KEY idx_collection_batches_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS collection_tasks (
  id BIGINT NOT NULL AUTO_INCREMENT,
  task_no VARCHAR(64) NOT NULL,
  batch_id BIGINT NULL,
  user_id BIGINT NOT NULL,
  chain_key VARCHAR(32) NOT NULL,
  coin_symbol VARCHAR(32) NOT NULL,
  asset_chain_id BIGINT NULL,
  from_address VARCHAR(128) NOT NULL,
  to_address VARCHAR(128) NOT NULL,
  amount DECIMAL(36,18) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  reason VARCHAR(255) NULL,
  tx_hash VARCHAR(128) NULL,
  block_number BIGINT NULL,
  gas_task_id BIGINT NULL,
  idempotency_key VARCHAR(128) NULL,
  retry_count INT NOT NULL DEFAULT 0,
  max_retry INT NOT NULL DEFAULT 3,
  next_retry_at DATETIME NULL,
  last_error TEXT NULL,
  locked_at DATETIME NULL,
  sent_at DATETIME NULL,
  confirmed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_collection_tasks_task_no (task_no),
  UNIQUE KEY uk_collection_tasks_idempotency_key (idempotency_key),
  KEY idx_collection_tasks_batch (batch_id),
  KEY idx_collection_tasks_user (user_id),
  KEY idx_collection_tasks_chain_coin_status (chain_key, coin_symbol, status),
  KEY idx_collection_tasks_tx_hash (tx_hash),
  KEY idx_collection_tasks_status_next_retry (status, next_retry_at),
  KEY idx_collection_tasks_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS gas_tasks (
  id BIGINT NOT NULL AUTO_INCREMENT,
  task_no VARCHAR(64) NOT NULL,
  collection_task_id BIGINT NULL,
  user_id BIGINT NOT NULL,
  chain_key VARCHAR(32) NOT NULL,
  gas_coin_symbol VARCHAR(32) NOT NULL,
  from_address VARCHAR(128) NOT NULL,
  to_address VARCHAR(128) NOT NULL,
  target_balance DECIMAL(36,18) NULL,
  topup_amount DECIMAL(36,18) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  tx_hash VARCHAR(128) NULL,
  block_number BIGINT NULL,
  idempotency_key VARCHAR(128) NULL,
  retry_count INT NOT NULL DEFAULT 0,
  max_retry INT NOT NULL DEFAULT 3,
  next_retry_at DATETIME NULL,
  last_error TEXT NULL,
  locked_at DATETIME NULL,
  sent_at DATETIME NULL,
  confirmed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_gas_tasks_task_no (task_no),
  UNIQUE KEY uk_gas_tasks_idempotency_key (idempotency_key),
  KEY idx_gas_tasks_collection_task (collection_task_id),
  KEY idx_gas_tasks_user (user_id),
  KEY idx_gas_tasks_chain_status (chain_key, status),
  KEY idx_gas_tasks_tx_hash (tx_hash),
  KEY idx_gas_tasks_status_next_retry (status, next_retry_at),
  KEY idx_gas_tasks_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
