CREATE TABLE IF NOT EXISTS contract_symbols (
  id BIGINT NOT NULL AUTO_INCREMENT,
  symbol VARCHAR(64) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  category VARCHAR(20) NOT NULL,
  provider VARCHAR(20) NOT NULL,
  provider_symbol VARCHAR(64) NOT NULL,
  quote_asset VARCHAR(20) NOT NULL DEFAULT 'USDT',
  tp_sl_trigger_price_type VARCHAR(20) NOT NULL DEFAULT 'MARK_PRICE',
  price_precision INT NOT NULL DEFAULT 8,
  quantity_precision INT NOT NULL DEFAULT 8,
  min_quantity DECIMAL(36,18) NOT NULL DEFAULT 0,
  max_quantity DECIMAL(36,18) NOT NULL DEFAULT 0,
  min_margin DECIMAL(36,18) NOT NULL DEFAULT 0,
  max_leverage INT NOT NULL DEFAULT 1,
  spread_x DECIMAL(36,18) NOT NULL DEFAULT 0,
  liquidation_threshold DECIMAL(36,18) NOT NULL DEFAULT 0,
  warning_threshold DECIMAL(36,18) NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_contract_symbols_symbol (symbol),
  KEY idx_contract_symbols_category (category),
  KEY idx_contract_symbols_provider (provider),
  KEY idx_contract_symbols_status (status),
  CONSTRAINT ck_contract_symbols_spread_x_range CHECK (spread_x >= 0 AND spread_x <= 50),
  CONSTRAINT ck_contract_symbols_max_leverage_range CHECK (max_leverage >= 1 AND max_leverage <= 200),
  CONSTRAINT ck_contract_symbols_status CHECK (status IN (0, 1)),
  CONSTRAINT ck_contract_symbols_tp_sl_trigger_price_type CHECK (tp_sl_trigger_price_type IN ('MARK_PRICE', 'LAST_PRICE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_accounts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  margin_asset VARCHAR(20) NOT NULL DEFAULT 'USDT',
  available_margin DECIMAL(36,18) NOT NULL DEFAULT 0,
  frozen_margin DECIMAL(36,18) NOT NULL DEFAULT 0,
  position_margin DECIMAL(36,18) NOT NULL DEFAULT 0,
  realized_pnl DECIMAL(36,18) NOT NULL DEFAULT 0,
  unrealized_pnl DECIMAL(36,18) NOT NULL DEFAULT 0,
  version BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_contract_accounts_user_asset (user_id, margin_asset),
  KEY idx_contract_accounts_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_positions (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  symbol VARCHAR(64) NOT NULL,
  side VARCHAR(10) NOT NULL,
  margin_mode VARCHAR(20) NOT NULL DEFAULT 'ISOLATED',
  leverage INT NOT NULL,
  quantity DECIMAL(36,18) NOT NULL,
  entry_price DECIMAL(36,18) NOT NULL,
  mark_price DECIMAL(36,18) NOT NULL DEFAULT 0,
  margin_amount DECIMAL(36,18) NOT NULL,
  open_fee DECIMAL(36,18) NOT NULL DEFAULT 0,
  unrealized_pnl DECIMAL(36,18) NOT NULL DEFAULT 0,
  realized_pnl DECIMAL(36,18) NOT NULL DEFAULT 0,
  liquidation_price DECIMAL(36,18) NOT NULL DEFAULT 0,
  warning_price DECIMAL(36,18) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_contract_positions_user (user_id),
  KEY idx_contract_positions_symbol (symbol),
  KEY idx_contract_positions_user_symbol_status (user_id, symbol, status),
  KEY idx_contract_positions_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_orders (
  id BIGINT NOT NULL AUTO_INCREMENT,
  order_no VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  symbol VARCHAR(64) NOT NULL,
  side VARCHAR(10) NOT NULL,
  position_side VARCHAR(10) NOT NULL,
  action VARCHAR(10) NOT NULL,
  order_type VARCHAR(20) NOT NULL,
  price DECIMAL(36,18) NULL,
  quantity DECIMAL(36,18) NOT NULL,
  leverage INT NOT NULL,
  margin_amount DECIMAL(36,18) NOT NULL,
  spread_x_snapshot DECIMAL(36,18) NOT NULL DEFAULT 0,
  spread_fee DECIMAL(36,18) NOT NULL DEFAULT 0,
  trigger_price DECIMAL(36,18) NULL,
  filled_quantity DECIMAL(36,18) NOT NULL DEFAULT 0,
  avg_price DECIMAL(36,18) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'NEW',
  fail_reason VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_contract_orders_order_no (order_no),
  KEY idx_contract_orders_user (user_id),
  KEY idx_contract_orders_symbol (symbol),
  KEY idx_contract_orders_user_symbol_status (user_id, symbol, status),
  KEY idx_contract_orders_status_created_at (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_trades (
  id BIGINT NOT NULL AUTO_INCREMENT,
  trade_no VARCHAR(64) NOT NULL,
  order_id BIGINT NOT NULL,
  position_id BIGINT NULL,
  user_id BIGINT NOT NULL,
  symbol VARCHAR(64) NOT NULL,
  side VARCHAR(10) NOT NULL,
  position_side VARCHAR(10) NOT NULL,
  action VARCHAR(10) NOT NULL,
  price DECIMAL(36,18) NOT NULL,
  quantity DECIMAL(36,18) NOT NULL,
  notional DECIMAL(36,18) NOT NULL,
  leverage INT NOT NULL,
  margin_amount DECIMAL(36,18) NOT NULL,
  spread_fee DECIMAL(36,18) NOT NULL DEFAULT 0,
  realized_pnl DECIMAL(36,18) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_contract_trades_trade_no (trade_no),
  KEY idx_contract_trades_order (order_id),
  KEY idx_contract_trades_position (position_id),
  KEY idx_contract_trades_user (user_id),
  KEY idx_contract_trades_symbol (symbol),
  KEY idx_contract_trades_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_margin_logs (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  position_id BIGINT NULL,
  order_id BIGINT NULL,
  symbol VARCHAR(64) NULL,
  change_type VARCHAR(40) NOT NULL,
  change_amount DECIMAL(36,18) NOT NULL,
  before_available DECIMAL(36,18) NOT NULL,
  after_available DECIMAL(36,18) NOT NULL,
  before_frozen DECIMAL(36,18) NOT NULL,
  after_frozen DECIMAL(36,18) NOT NULL,
  remark VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_contract_margin_logs_user (user_id),
  KEY idx_contract_margin_logs_account (account_id),
  KEY idx_contract_margin_logs_position (position_id),
  KEY idx_contract_margin_logs_order (order_id),
  KEY idx_contract_margin_logs_change_type (change_type),
  KEY idx_contract_margin_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_liquidation_records (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  position_id BIGINT NOT NULL,
  symbol VARCHAR(64) NOT NULL,
  side VARCHAR(10) NOT NULL,
  leverage INT NOT NULL,
  quantity DECIMAL(36,18) NOT NULL,
  entry_price DECIMAL(36,18) NOT NULL,
  mark_price DECIMAL(36,18) NOT NULL,
  liquidation_price DECIMAL(36,18) NOT NULL,
  margin_amount DECIMAL(36,18) NOT NULL,
  unrealized_pnl DECIMAL(36,18) NOT NULL,
  remaining_amount DECIMAL(36,18) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'TRIGGERED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_contract_liquidation_records_user (user_id),
  KEY idx_contract_liquidation_records_position (position_id),
  KEY idx_contract_liquidation_records_symbol (symbol),
  KEY idx_contract_liquidation_records_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
