import { VipPageMockData } from './vip.types';

export const vipPageMock: VipPageMockData = {
  hero: {
    eyebrow: '会员体系总览',
    title: 'VIP 与 SVIP 会员中心',
    description:
      '动态 VIP 依据近 30 天交易量与 RCB 非锁仓持仓评估，静态 SVIP 依据 RCB 锁仓量与锁仓周期评估，两套体系并行展示。',
    highlights: ['深色金阶视觉', '双栏平行结构', 'Mock 数据可替换接口'],
  },
  overviews: {
    vip: {
      type: 'VIP',
      title: 'VIP 当前状态',
      subtitle: '动态等级根据近 30 天交易量与 RCB 非锁仓持仓变化实时评估。',
      levelCode: 'VIP3',
      levelName: '高频交易会员',
      status: '已命中',
      progressLabel: '距离 VIP4 还需补足',
      progressPercent: 68,
      progressCurrent: '30天交易量 680,000 USDT',
      progressTarget: '目标 1,000,000 USDT',
      metrics: [
        { label: '30天交易量', value: '680,000 USDT', hint: '已计入现货与合约成交量' },
        { label: 'RCB非锁仓持有量', value: '18,500 RCB', hint: '可随持仓变化动态更新' },
        { label: '当前 Spot Maker', value: '0.0005000000' },
        { label: '当前 Spot Taker', value: '0.0007000000' },
      ],
    },
    svip: {
      type: 'SVIP',
      title: 'SVIP 当前状态',
      subtitle: '静态等级根据 RCB 锁仓量与锁仓周期判定，适合长期持有用户。',
      levelCode: 'SVIP2',
      levelName: '锁仓分红会员',
      status: '已生效',
      progressLabel: '距离 SVIP3 还需补足',
      progressPercent: 42,
      progressCurrent: '锁仓 120,000 RCB / 90 天',
      progressTarget: '目标 300,000 RCB / 180 天',
      metrics: [
        { label: 'RCB锁仓量', value: '120,000 RCB', hint: '统计当前生效锁仓单' },
        { label: '锁仓周期', value: '90 天', hint: '锁仓周期越长可命中更高等级' },
        { label: '当前 Spot Maker', value: '0.0004000000' },
        { label: '当前 Spot Taker', value: '0.0006500000' },
      ],
    },
  },
  systems: [
    {
      type: 'VIP',
      title: 'VIP等级体系（动态）',
      subtitle: '根据近 30 天交易量与 RCB 非锁仓持有量动态命中等级。',
      badge: 'Dynamic',
      levels: [
        {
          levelCode: 'VIP0',
          levelName: '普通用户',
          min30dVolume: '0',
          minRcbHold: '0',
          spotMakerFee: '0.0010000000',
          spotTakerFee: '0.0010000000',
          rcbDiscountRate: '0.0000000000',
        },
        {
          levelCode: 'VIP1',
          levelName: '交易进阶',
          min30dVolume: '50,000',
          minRcbHold: '2,000',
          spotMakerFee: '0.0008000000',
          spotTakerFee: '0.0009000000',
          rcbDiscountRate: '0.0500000000',
        },
        {
          levelCode: 'VIP2',
          levelName: '活跃做市',
          min30dVolume: '250,000',
          minRcbHold: '8,000',
          spotMakerFee: '0.0006500000',
          spotTakerFee: '0.0008000000',
          rcbDiscountRate: '0.1200000000',
        },
        {
          levelCode: 'VIP3',
          levelName: '高频交易会员',
          isCurrent: true,
          min30dVolume: '500,000',
          minRcbHold: '15,000',
          spotMakerFee: '0.0005000000',
          spotTakerFee: '0.0007000000',
          rcbDiscountRate: '0.1800000000',
        },
        {
          levelCode: 'VIP4',
          levelName: '旗舰交易会员',
          min30dVolume: '1,000,000',
          minRcbHold: '30,000',
          spotMakerFee: '0.0003500000',
          spotTakerFee: '0.0005500000',
          rcbDiscountRate: '0.2500000000',
        },
      ],
      rulesTitle: 'VIP 规则说明',
      rulesSubtitle: '本栏只解释动态 VIP 的命中与更新方式。',
      rules: [
        {
          title: '动态评估窗口',
          description: 'VIP 依据近 30 天累计交易量与 RCB 非锁仓持有量综合判断，任一指标变化都会影响等级结果。',
        },
        {
          title: '非锁仓持仓口径',
          description: '这里只统计未参与锁仓计划的 RCB 持仓，用于区分动态交易权益与静态锁仓权益。',
        },
        {
          title: '费率与折扣展示',
          description: '列表展示 Spot Maker、Spot Taker 与 RCB 折扣，后续可直接替换为接口字段输出。',
        },
      ],
    },
    {
      type: 'SVIP',
      title: 'SVIP等级体系（静态）',
      subtitle: '根据 RCB 锁仓量、锁仓周期以及静态席位规则命中等级。',
      badge: 'Static',
      levels: [
        {
          levelCode: 'SVIP1',
          levelName: '锁仓会员',
          minLockAmount: '50,000',
          lockPeriodDays: '30 天',
          userLimit: '200',
          dividendRate: '0.0500000000',
          spotMakerFee: '0.0006000000',
          spotTakerFee: '0.0008500000',
          rcbDiscountRate: '0.1500000000',
        },
        {
          levelCode: 'SVIP2',
          levelName: '锁仓分红会员',
          isCurrent: true,
          minLockAmount: '120,000',
          lockPeriodDays: '90 天',
          userLimit: '120',
          dividendRate: '0.0800000000',
          spotMakerFee: '0.0004000000',
          spotTakerFee: '0.0006500000',
          rcbDiscountRate: '0.2200000000',
        },
        {
          levelCode: 'SVIP3',
          levelName: '核心锁仓会员',
          minLockAmount: '300,000',
          lockPeriodDays: '180 天',
          userLimit: '60',
          dividendRate: '0.1200000000',
          spotMakerFee: '0.0002500000',
          spotTakerFee: '0.0005000000',
          rcbDiscountRate: '0.3000000000',
        },
        {
          levelCode: 'LP',
          levelName: '流动性合伙人',
          minLockAmount: '800,000',
          lockPeriodDays: '365 天',
          userLimit: '20',
          dividendRate: '0.1800000000',
          spotMakerFee: '0.0001000000',
          spotTakerFee: '0.0003500000',
          rcbDiscountRate: '0.4000000000',
        },
      ],
      rulesTitle: 'SVIP 规则说明',
      rulesSubtitle: '本栏只解释静态 SVIP 的锁仓与名额规则。',
      rules: [
        {
          title: '锁仓口径',
          description: 'SVIP 依据已生效锁仓单计算，锁仓量与锁仓周期需要同时满足对应档位的门槛。',
        },
        {
          title: '人数上限',
          description: '部分静态等级存在人数上限，用于控制席位稀缺性与分红占比配置。',
        },
        {
          title: '分红比例',
          description: 'SVIP 栏位会额外展示分红比例，便于后续直接替换为真实配置与用户实际命中结果。',
        },
      ],
    },
  ],
  feeNotice: 'VIP 与 SVIP 并行计算，实际手续费按两套体系中更低费率执行。',
};
